### ISSUE TITLE
Failed to run bevy

### ISSUE THREAD

**Issue by Yairama** [virtualritz/polyhedron-operators#14]
hello!

I have a problem when run:
`cargo run --release --example bevy --features "bevy"`

the output is:
`error: failed to run custom build command for smithay-client-toolkit v0.16.0`

The same error appears when I use the bevy feature in project integration.

Also, the version in crates.io is 0.2.3, can you update it please?

**Comment by virtualritz** [comment]
I'll check but this error looks to be coming from a dependency.
On which platform are you trying to build?

**Comment by Yairama** [comment]
Nice!
Ubuntu 22.04.1 LTS 64 bits

**Comment by virtualritz** [comment]
I think this is related to the `wayland` feature on `bevy`.
I can not replicate this on the same Ubuntu version as you. I suggest trying to swap the `wayland` for the `x11` feature on the `bevy` dependency.

That said, I found an issue when adapting the example to `bevy` `0.9` but I am waiting for feedback from the bevy community to solve this. There will be an update to this crate once that is fixed.

**Comment by virtualritz** [comment]
I updated the `bevy` example for `bevy 0.9` and published an updated version of the crate (`.0.2.4`).
